### PR TITLE
Tweaked SEE ALSO (and some other things)

### PR DESCRIPTION
**Pull request by neilb**
Hi Mohammad,

I started off just wanting to add an `L<...>` link about the one module in SEE ALSO, but ended up doing a couple of others things :-)

Cheers,
Neil

### CODE REVIEW

**Comment by neilb** [comment]
You could also set the min perl version in the `Makefile.PL`, and add the TEST_REQUIRES as well :-)

**Comment by manwar** [comment]
Thanks Neil for the PR. This is probably the first PR, I have received from you 😀
It was on my TODO list 😉
I pushed v0.03 this morning and found it flagged as "Unauthorised". Any idea why?

Best Regards,
Mohammad S Anwar

**Comment by neilb** [comment]
> I pushed v0.03 this morning and found it flagged as "Unauthorised". Any idea why?

I think it just a timing thing with MetaCPAN — they saw your release, but hadn’t picked up the latest 06perms.txt file from CPAN. They had a cached copy, and in that you didn’t have ownership of File::Same. Eventually they picked up a new copy of 06perms.txt, in which you did have ownership, which is why it’s not flagged as unauthorized any more.

Cheers,
Neil

**Comment by manwar** [comment]
Thanks for the prompt and detailed reply.
I learn something new every day. 😀

Best Regards,
Mohammad S Anwar

**Pull request merged**
